parameters:
- name: 'restoreProjects'
  default: ''
  type: string
- name: 'buildProjects'
  default: ''
  type: string

steps:
- script: echo ${{ and(eq(variables.letters, 'bac'), eq(variables.numbers, 123)) }}